### ISSUE TITLE
strange content added during object removal with large masked areas

### ISSUE THREAD

**Issue by ai-ls** [zhuang2002/PowerPaint#101]
Hello, thank you for your open-source work.
I'm encountering some issues while using the Object Removal feature. Generally, I don’t need to input a prompt or negative prompt, and when the masked area is relatively small, it can be removed effectively. However, when the masked area is larger, even if I input a prompt (like "nothing") and a negative prompt (like "people, letters, markings"), the removal often results in the addition of strange content in the masked area. Below are my test results and the test image. I would like to know if there are any solutions or ideas for this issue. 
Looking forward to your reply.

<img width="1158" alt="Snipaste_2024-10-09_11-02-02" src="https://github.com/user-attachments/assets/703d475a-8c5d-485b-897f-280e588f4746">

<img width="1154" alt="Snipaste_2024-10-09_11-03-30" src="https://github.com/user-attachments/assets/13991a4e-b465-4a5c-9021-2a3588ddfb81">

![test_1024](https://github.com/user-attachments/assets/1409afed-2ec0-4f24-b23c-b70c34e42d96)

**Comment by zengyh1900** [comment]
hi @xnyd-ls 

This is because we use LAION for training, and those images often contain meaningful and apparent objects in the large central region of the image. If you want to improve the performance of object removal, fine-tuning on a background dataset could be beneficial.

**Comment by ai-ls** [comment]
Thank you for your reply!
