### ISSUE TITLE
更换运行gpu

### ISSUE THREAD

**Issue by mocha1908** [zhuang2002/PowerPaint#109]
你好，我是调用ppt-v2-1这个里面的模型，然后我想把整个代码都放在指定的gpu上，但是我在主代码中将模型放在指定的gpu上，后面导入外部模型开始运行后还是修改在默认gpu上，如何修改代码或者做其他操作，让整体包括过程中所有代码在指定gpu上？

**Comment by zengyh1900** [comment]
hi  @mocha1908 
主要是两个地方可以修改模型的设备：
1. 权重加载，通过 map_location 来指定权重的位置；
2. 模型初始化以及加载权重后，通过 `.to(device)` 的操作来指定；

你可以打印你的设备信息来看看，各个模型是否放到了正确的位置。具体地，可以参考 pytorch 的文档。
