### ISSUE TITLE
消除后，其他区域会重绘

### ISSUE THREAD

**Issue by fuchao01** [zhuang2002/PowerPaint#111]
<img width="622" alt="企业微信20241016-155859@2x" src="https://github.com/user-attachments/assets/c17d594f-3839-4e8e-822c-43438e7de242">

![image (1)](https://github.com/user-attachments/assets/ebef98f0-4039-42bf-8805-f0c059f43a99)

消除左右两个人，但是中间的人会重绘，特别是脸部，这个是什么原因造成的

**Comment by zengyh1900** [comment]
hi @fuchao01 

看样子，你主要是用了我们的 demo 来测试的，主要原因可能：
1. 图像 resize 了，修改了分辨率
2. VAE 对人脸的重建有损失

建议可以修改代码，去掉过分的 resize 操作，或者把output 通过mask 贴回原图。

另外，你这里的结果又出现了新的人，这个原因是因为你的mask没有完全覆盖掉人，留了一些边缘，模型有bias容易重建生成出新的东西；建议mask可以改进下。

**Comment by fuchao01** [comment]
<img width="676" alt="image" src="https://github.com/user-attachments/assets/2f1c77b9-7359-4a83-a8d7-3ce74945b36f">

检查了下代码，没有发现mask不准。也把输入图片resize成最小边640了，也不行。你说说的resize指的的哪里呢
