### ISSUE TITLE
Some prompt may cause problem

### ISSUE THREAD

**Issue by YuzhenD** [zhuang2002/PowerPaint#112]
I try to use PowePaint for background generation，but sometimes meet the following problem:

./PowerPaint/powerpaint/utils/utils.py", line 429, in replace_embeddings
    assert actually_ids_to_replace == target_ids_to_replace, (
AssertionError: Invalid 'input_ids' in position: 0 to 75. Expect '[49428, 49429, 49430, 49431, 49432, 49433, 49434, 49435, 49436, 49437]' for embedding 'P_obj' but found '[49428, 49407]'.

Model : PPT-v1
Task : text-guided
Prompt: The shampoo bottles are placed in the shampoo area of a high-end hair salon, with a backdrop of elegantly decorated styling chairs and professional shampooing equipment. The shampoo bottles are neatly arranged alongside other hair care products, exuding an elegant and stylish appearance under the soft lighting. The entire environment is infused with professionalism and fashion, resembling an advertising photograph.
Negative_Prompt: Left and right, four-grid, nine-grid, incorrect eyes, bad faces, nudity, canvas frame, disfigurement, bad art, deformation, extra limbs, close-up, black and white, blurred colors, blur, repetition, morbid, incomplete, frame.

**Comment by zengyh1900** [comment]
Hi @YuzhenD, 

It feels like you failed to import the right prompts. Did you modify anything? Or have you successfully load all pretrained models?

**Comment by YuzhenD** [comment]
Hi @zengyh1900,
I try to mobify the app.py of powerpaint for my test. The following is the code for shape-guided task:
<img width="743" alt="4" src="https://github.com/user-attachments/assets/3dcd64a5-fda1-44ce-a967-863428d7262c">
I further modify it for batch inference, but some case may meet this problem:
<img width="969" alt="5" src="https://github.com/user-attachments/assets/163f834e-f230-4759-9604-a09d3647d10a">
I try to print the prompt_A, prompt_B, neg_prompt_A, neg_prompt_B. It seems to import the right prompt, but some case may not work.

**Comment by YuzhenD** [comment]
This is casued by too long prompts, since CLIP can only handle sequences up tp 77 tokens.
