### ISSUE TITLE
Running app.py raises errors

### ISSUE THREAD

**Issue by Rayjryang** [zhuang2002/PowerPaint#118]
#### Problem Description

I'm trying to run `app.py` with the following command:

```bash
python app.py --share --version ppt-v2 --checkpoint_dir checkpoints/ppt-v2
```

However, it throws the following error:

```
usage: app.py [-h] --pretrained_model_path PRETRAINED_MODEL_PATH [--base_model_path BASE_MODEL_PATH] [--weight_dtype WEIGHT_DTYPE] [--share] [--local_files_only] [--port PORT]
app.py: error: the following arguments are required: --pretrained_model_path
```

#### Attempts to Solve the Issue

I tried setting `pretrained_model_path` directly in `app.py` as `ppt2`, but encountered another error:

```
usage: app.py [-h] [--pretrained_model_path PRETRAINED_MODEL_PATH] [--base_model_path BASE_MODEL_PATH] [--weight_dtype WEIGHT_DTYPE] [--share] [--local_files_only] [--port PORT]
app.py: error: unrecognized arguments: --version ppt-v2 --checkpoint_dir checkpoints/ppt-v2
```

Could you please advise on:
1. How to correctly specify `pretrained_model_path` and other required arguments?
2. Whether `--version` and `--checkpoint_dir` are supported parameters, and if so, how they should be used?

Thank you!

**Comment by x4080** [comment]
Hi, how do you solve this problem ?

**Comment by Rayjryang** [comment]
Sure. The reason is that the README file doesn't match the dev branch. Switching to the main branch can solve this issue.

**Comment by x4080** [comment]
@Rayjryang Thanks for answering
