### ISSUE TITLE
Cannot run Gradio Interface

### ISSUE THREAD

**Issue by HelloRheina** [zhuang2002/PowerPaint#124]
I tried to run Gradio Interface as instructed on the ReadMe
git lfs clone https://huggingface.co/JunhaoZhuang/PowerPaint_v2/ ./checkpoints/ppt-v2

python app.py --share --version ppt-v2 --checkpoint_dir checkpoints/ppt-v2

usage: app.py [-h] --pretrained_model_path PRETRAINED_MODEL_PATH
              [--base_model_path BASE_MODEL_PATH]
              [--weight_dtype WEIGHT_DTYPE] [--share] [--local_files_only]
              [--port PORT]
app.py: error: the following arguments are required: --pretrained_model_path

may I know what is the updated pretrained_model_path? I used ppt-v2, but it said config.json does not exist

**Comment by Haderob** [comment]
git checkout main
