### ISSUE TITLE
app.py error

### ISSUE THREAD

**Issue by kingfall** [zhuang2002/PowerPaint#132]
![捕获](https://github.com/user-attachments/assets/65b5cb1d-33cb-4965-a12b-0ea424f9eac9)
启动app.py时出现错误，需要预训练模型地址
![image](https://github.com/user-attachments/assets/296eb6f6-695c-474f-bcf6-a5124e38f425)
app.py内也没有checkpoints和version的参数，望解答谢谢

**Comment by IridescentJiang** [comment]
是不是没有切main分支？你说的问题在dev分支里会存在

**Comment by qing-24** [comment]
> 是不是没有切主分支？你说的问题在dev分支里会存在

有点不懂

**Comment by qing-24** [comment]
> 是不是没有切main分支？你说的问题在dev分支里会存在

main分支也错误

**Comment by hikakaaaa** [comment]
我也遇到了同样问题，请问如何解决

**Comment by qing-24** [comment]
> 我也遇到了同样的问题，请问如何解决

克隆main分支解决问题
