### ISSUE TITLE
How to do batch inference?

### ISSUE THREAD

**Issue by Bokai-Ji** [zhuang2002/PowerPaint#133]
Hi,

Thank you for the amazing work and for providing this repository!

I have images and pre-extracted masks for object removal, and I modified `app.py` to perform automatic inference. However, I noticed that the `PowerPaintController` currently processes only one sample at a time during inference.

Is there an example or guidance available for implementing batch inference? Any pointers would be greatly appreciated!

Thank you for your time and assistance!

**Comment by Bokai-Ji** [comment]
Solved

**Comment by rzhevcherkasy** [comment]
Hi, could you please kindly share how you modified the code to enable batch inference? Thank you so much!

**Comment by IridescentJiang** [comment]
Hi, could you please share how to modify the code to implement batch inference? Thanks a lot!

**Comment by xiao10ma** [comment]
Hi, could you please share how to modify the code to implement batch inference? Thanks a lot!

**Comment by autelcss** [comment]
Hi, could you please share how to modify the code to implement batch inference? Thanks a lot!
