### ISSUE TITLE
Missing model of PowerPaint_v2

### ISSUE THREAD

**Issue by dydxdt** [zhuang2002/PowerPaint#27]
Thanks for your great work!
When I run 'python gradio_PowerPaint_BrushNet.py', I met this error: 
OSError: Error no file named diffusion_pytorch_model.bin found in directory ./PowerPaint_v2/realisticVisionV60B1_v51VAE/unet.

I find that this diffusion_pytorch_model.bin is not in the huggingface repo. Where can I get this model? Many thanks.

**Comment by zhuang2002** [comment]
Thanks for your interest, you can try downloading from openxlab(https://openxlab.org.cn/models/detail/zhuangjunhao/PowerPaint_v2). I will immediately complete the model weights in huggingface
