### ISSUE TITLE
email error

### ISSUE THREAD

**Issue by xinli2008** [zhuang2002/PowerPaint#3]
The email address zhuangjunhao@mails.tsinghua.edu.cn seems broken, can you provide another right email address?

**Comment by zhuang2002** [comment]
> The email address [zhuangjunhao@mails.tsinghua.edu.cn](mailto:zhuangjunhao@mails.tsinghua.edu.cn) seems broken, can you provide another right email address?

I apologize; my email is [zhuangjh23@mails.tsinghua.edu.cn](mailto:zhuangjh23@mails.tsinghua.edu.cn). I have already made corrections on arXiv.

**Comment by xinli2008** [comment]
您的邮箱服务器似乎没有反应，邮件一直发不出去，我的问题如下：
----------------------------------------------------------------------------------------------------
您好，感谢您将powerpaint开源，阅读了您的powerpaint论文后，我有几个问题想请教一下：
1、powerpaint的思路大概是训练过程中添加了可以训练的task prompt，然后在推理的时候根据不同的推理任务，搭配使用训练好的task prompt，但是论文中似乎没有过多的提到训练策略。比如我现在有1W条数据，分别是 原图/mask/txt_file，如何在训练的时候分配这些数据呢？比如说百分之多少用于P_obj，百分之多少用于训练P_ctxt等等。您可以讲解一下吗？您在训练的时候是将多种不同的数据组合一起训练的吗？
2、关于outapint，您在训练outpaint的时候，使用的mask是外扩的mask吗？即中间是黑色，外面是白色 的训练样本吗？
3、关于在您提供文件上微调的可能性，我注意到您提供了text_encoder和unet，将pipeline搭配到一起的话，我应该是可以使用lora在该模型上进行微调的。。但是我很好奇的是，由于你的模型已经具有了多种inapint的能力，要是在上面微调的话，训练数据只需要准备一种就可以了，而是说要准备多种？
