### ISSUE TITLE
Is it better than fooocus inpaint?

### ISSUE THREAD

**Issue by wodsoe** [zhuang2002/PowerPaint#37]
Is it better than fooocus inpaint?

**Comment by dydxdt** [comment]
seems that fooocus is a littele bit better

**Comment by viperyl** [comment]
accourding to my experiment so far, train powerpaint with SDXL + fooocus can achive amazing result

**Comment by zengyh1900** [comment]
> accourding to my experiment so far, train powerpaint with SDXL + fooocus can achive amazing result

wow!! :star_struck: Would you mind sharing some results?

**Comment by foocker** [comment]
> accourding to my experiment so far, train powerpaint with SDXL + fooocus can achive amazing result

？detail?

**Comment by foocker** [comment]
> 似乎 Fooocus 更好一点

is there any magic? i have test the inpaint from Fooocus, the result is bad, such as artifact, some other genere content and so on.

**Comment by foocker** [comment]
> seems that fooocus is a littele bit better

is there any magic? i have test the inpaint from Fooocus, the result is bad, such as artifact, some other genere content and so on.
