### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by andriyrizhiy** [zhuang2002/PowerPaint#5]
Awesome paper! Will you publish the training code? It is interesting to try with other versions of SD

**Comment by zhuang2002** [comment]
Yes, indeed! We plan to release the training code in the future and intend to carry out the training on a more advanced version of Stable Diffusion.

**Comment by andriyrizhiy** [comment]
Thank you, waiting for the release!

**Comment by igodogi** [comment]
> Yes, indeed! We plan to release the training code in the future and intend to carry out the training on a more advanced version of Stable Diffusion.

When will the codes be released?

**Comment by dydxdt** [comment]
> Yes, indeed! We plan to release the training code in the future and intend to carry out the training on a more advanced version of Stable Diffusion.

Also waiting for the release!

**Comment by CharlesGong12** [comment]
Hi, how long will you release training code? Waiting for it!

**Comment by foocker** [comment]
why closed?(training code is not relase)

**Comment by zengyh1900** [comment]
Hi all and  @foocker 

Thank you for your interest and for being so patient :)
We have released our training configurations and scripts for both [train_ppt1_sd15.py](https://github.com/open-mmlab/PowerPaint/blob/dev/train_ppt1_sd15.py) for unet-based version and [train_ppt2_bn.py](https://github.com/open-mmlab/PowerPaint/blob/dev/train_ppt2_bn.py) for brushnet-based version.
