### ISSUE TITLE
Running Issue

### ISSUE THREAD

**Issue by Chinafsh** [zhuang2002/PowerPaint#73]
My OS is Ubuntu 22.04, I followed the install suggestion to install PowerPaint. Finally, I run "python app.py --share --version ppt-v2 --checkpoint_dir checkpoints/ppt-v2", then I go to my local URL, load image, do some mask, button Run, however, I get an error, there is no result.
![Screenshot from 2024-08-30 13-31-03](https://github.com/user-attachments/assets/7ede2db3-30c0-4530-a218-424a8f2ca009)
![Screenshot from 2024-08-30 13-30-38](https://github.com/user-attachments/assets/a1f53cfd-c17e-406c-bc91-d50a55ba328b)

**Comment by Chinafsh** [comment]
> My OS is Ubuntu 22.04, I followed the install suggestion to install PowerPaint. Finally, I run "python app.py --share --version ppt-v2 --checkpoint_dir checkpoints/ppt-v2", then I go to my local URL, load image, do some mask, button Run, however, I get an error, there is no result. ![Screenshot from 2024-08-30 13-31-03](https://private-user-images.githubusercontent.com/92346207/363052059-7ede2db3-30c0-4530-a218-424a8f2ca009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTYxODEsIm5iZiI6MTcyNDk5NTg4MSwicGF0aCI6Ii85MjM0NjIwNy8zNjMwNTIwNTktN2VkZTJkYjMtMzBjMC00NTMwLWEyMTgtNDI0YThmMmNhMDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA1MzEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MGEzOTU2MTJmYzI0MmUxNzljOGQ0OGQyNTEwZTczM2JhYWFjYmFjY2U4OGE4ZWNlZjQ3MWRiMTk5YzA4N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JBHVALzTuaFrhqhwlo6t2VILhYsgjXA5ZJ5zqG7dPSE) ![Screenshot from 2024-08-30 13-30-38](https://private-user-images.githubusercontent.com/92346207/363052074-a1f53cfd-c17e-406c-bc91-d50a55ba328b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTYxODEsIm5iZiI6MTcyNDk5NTg4MSwicGF0aCI6Ii85MjM0NjIwNy8zNjMwNTIwNzQtYTFmNTNjZmQtYzE3ZS00MDZjLWJjOTEtZDUwYTU1YmEzMjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA1MzEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhY2Q2YWM0ODVhZGE4NTQxMWRiYjg2ODAxNDI5MTYzMTE4ZTE4ZjQzMjlkNDc0Y2JjN2NhZjUxYmQ2ZmZmNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g0NegcJDQ28gcAr_OD0BMXRT77cPtEYLOmcDlGwAeBA)

@zhuang2002 @zengyh1900 
![Screenshot from 2024-08-30 13-46-28](https://github.com/user-attachments/assets/e08c1689-14b7-4139-b936-761e70b909f1)

it stucks, could u guys help me.

**Comment by PlanPersisitentPatient** [comment]
> > My OS is Ubuntu 22.04, I followed the install suggestion to install PowerPaint. Finally, I run "python app.py --share --version ppt-v2 --checkpoint_dir checkpoints/ppt-v2", then I go to my local URL, load image, do some mask, button Run, however, I get an error, there is no result. ![Screenshot from 2024-08-30 13-31-03](https://private-user-images.githubusercontent.com/92346207/363052059-7ede2db3-30c0-4530-a218-424a8f2ca009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTYxODEsIm5iZiI6MTcyNDk5NTg4MSwicGF0aCI6Ii85MjM0NjIwNy8zNjMwNTIwNTktN2VkZTJkYjMtMzBjMC00NTMwLWEyMTgtNDI0YThmMmNhMDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA1MzEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MGEzOTU2MTJmYzI0MmUxNzljOGQ0OGQyNTEwZTczM2JhYWFjYmFjY2U4OGE4ZWNlZjQ3MWRiMTk5YzA4N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JBHVALzTuaFrhqhwlo6t2VILhYsgjXA5ZJ5zqG7dPSE) ![Screenshot from 2024-08-30 13-30-38](https://private-user-images.githubusercontent.com/92346207/363052074-a1f53cfd-c17e-406c-bc91-d50a55ba328b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTYxODEsIm5iZiI6MTcyNDk5NTg4MSwicGF0aCI6Ii85MjM0NjIwNy8zNjMwNTIwNzQtYTFmNTNjZmQtYzE3ZS00MDZjLWJjOTEtZDUwYTU1YmEzMjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA1MzEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhY2Q2YWM0ODVhZGE4NTQxMWRiYjg2ODAxNDI5MTYzMTE4ZTE4ZjQzMjlkNDc0Y2JjN2NhZjUxYmQ2ZmZmNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g0NegcJDQ28gcAr_OD0BMXRT77cPtEYLOmcDlGwAeBA)
> 
> @zhuang2002 @zengyh1900 ![Screenshot from 2024-08-30 13-46-28](https://private-user-images.githubusercontent.com/92346207/363055151-e08c1689-14b7-4139-b936-761e70b909f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MzUxMDIsIm5iZiI6MTczMDQzNDgwMiwicGF0aCI6Ii85MjM0NjIwNy8zNjMwNTUxNTEtZTA4YzE2ODktMTRiNy00MTM5LWI5MzYtNzYxZTcwYjkwOWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA0MjAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4M2RlZGFjMWJmZDk4YzQ0Mzg2ZThmM2Q4NTQ1YmUyMWE5M2YwMmI1MWFkMDg3YmQ2ODMxYzZmZTkwMjk4ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IMZ6EIj45iRPyc3fnDTNO-T_RznuL6JJI295fPJh3v8)
> 
> it stucks, could u guys help me.

I'm experiencing the same problem. Could you please let me know how you addressed it? I would really appreciate your help.

**Comment by Chinafsh** [comment]
> > > My OS is Ubuntu 22.04, I followed the install suggestion to install PowerPaint. Finally, I run "python app.py --share --version ppt-v2 --checkpoint_dir checkpoints/ppt-v2", then I go to my local URL, load image, do some mask, button Run, however, I get an error, there is no result. ![Screenshot from 2024-08-30 13-31-03](https://private-user-images.githubusercontent.com/92346207/363052059-7ede2db3-30c0-4530-a218-424a8f2ca009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTYxODEsIm5iZiI6MTcyNDk5NTg4MSwicGF0aCI6Ii85MjM0NjIwNy8zNjMwNTIwNTktN2VkZTJkYjMtMzBjMC00NTMwLWEyMTgtNDI0YThmMmNhMDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA1MzEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MGEzOTU2MTJmYzI0MmUxNzljOGQ0OGQyNTEwZTczM2JhYWFjYmFjY2U4OGE4ZWNlZjQ3MWRiMTk5YzA4N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JBHVALzTuaFrhqhwlo6t2VILhYsgjXA5ZJ5zqG7dPSE) ![Screenshot from 2024-08-30 13-30-38](https://private-user-images.githubusercontent.com/92346207/363052074-a1f53cfd-c17e-406c-bc91-d50a55ba328b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTYxODEsIm5iZiI6MTcyNDk5NTg4MSwicGF0aCI6Ii85MjM0NjIwNy8zNjMwNTIwNzQtYTFmNTNjZmQtYzE3ZS00MDZjLWJjOTEtZDUwYTU1YmEzMjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA1MzEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhY2Q2YWM0ODVhZGE4NTQxMWRiYjg2ODAxNDI5MTYzMTE4ZTE4ZjQzMjlkNDc0Y2JjN2NhZjUxYmQ2ZmZmNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g0NegcJDQ28gcAr_OD0BMXRT77cPtEYLOmcDlGwAeBA)
> > 
> > 
> > @zhuang2002 @zengyh1900 ![Screenshot from 2024-08-30 13-46-28](https://private-user-images.githubusercontent.com/92346207/363055151-e08c1689-14b7-4139-b936-761e70b909f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MzUxMDIsIm5iZiI6MTczMDQzNDgwMiwicGF0aCI6Ii85MjM0NjIwNy8zNjMwNTUxNTEtZTA4YzE2ODktMTRiNy00MTM5LWI5MzYtNzYxZTcwYjkwOWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA0MjAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4M2RlZGFjMWJmZDk4YzQ0Mzg2ZThmM2Q4NTQ1YmUyMWE5M2YwMmI1MWFkMDg3YmQ2ODMxYzZmZTkwMjk4ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IMZ6EIj45iRPyc3fnDTNO-T_RznuL6JJI295fPJh3v8)
> > it stucks, could u guys help me.
> 
> I'm experiencing the same problem. Could you please let me know how you addressed it? I would really appreciate your help.

hello, I didn't fix this problem. But I add some code in the source code, to get the result image and save it. It's easy to do it. hope this could help u.

**Comment by PlanPersisitentPatient** [comment]
> > > > My OS is Ubuntu 22.04, I followed the install suggestion to install PowerPaint. Finally, I run "python app.py --share --version ppt-v2 --checkpoint_dir checkpoints/ppt-v2", then I go to my local URL, load image, do some mask, button Run, however, I get an error, there is no result. ![Screenshot from 2024-08-30 13-31-03](https://private-user-images.githubusercontent.com/92346207/363052059-7ede2db3-30c0-4530-a218-424a8f2ca009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTYxODEsIm5iZiI6MTcyNDk5NTg4MSwicGF0aCI6Ii85MjM0NjIwNy8zNjMwNTIwNTktN2VkZTJkYjMtMzBjMC00NTMwLWEyMTgtNDI0YThmMmNhMDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA1MzEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MGEzOTU2MTJmYzI0MmUxNzljOGQ0OGQyNTEwZTczM2JhYWFjYmFjY2U4OGE4ZWNlZjQ3MWRiMTk5YzA4N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JBHVALzTuaFrhqhwlo6t2VILhYsgjXA5ZJ5zqG7dPSE) ![Screenshot from 2024-08-30 13-30-38](https://private-user-images.githubusercontent.com/92346207/363052074-a1f53cfd-c17e-406c-bc91-d50a55ba328b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTYxODEsIm5iZiI6MTcyNDk5NTg4MSwicGF0aCI6Ii85MjM0NjIwNy8zNjMwNTIwNzQtYTFmNTNjZmQtYzE3ZS00MDZjLWJjOTEtZDUwYTU1YmEzMjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA1MzEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhY2Q2YWM0ODVhZGE4NTQxMWRiYjg2ODAxNDI5MTYzMTE4ZTE4ZjQzMjlkNDc0Y2JjN2NhZjUxYmQ2ZmZmNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g0NegcJDQ28gcAr_OD0BMXRT77cPtEYLOmcDlGwAeBA)
> > > 
> > > 
> > > @zhuang2002 @zengyh1900 ![Screenshot from 2024-08-30 13-46-28](https://private-user-images.githubusercontent.com/92346207/363055151-e08c1689-14b7-4139-b936-761e70b909f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MzUxMDIsIm5iZiI6MTczMDQzNDgwMiwicGF0aCI6Ii85MjM0NjIwNy8zNjMwNTUxNTEtZTA4YzE2ODktMTRiNy00MTM5LWI5MzYtNzYxZTcwYjkwOWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA0MjAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4M2RlZGFjMWJmZDk4YzQ0Mzg2ZThmM2Q4NTQ1YmUyMWE5M2YwMmI1MWFkMDg3YmQ2ODMxYzZmZTkwMjk4ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IMZ6EIj45iRPyc3fnDTNO-T_RznuL6JJI295fPJh3v8)
> > > it stucks, could u guys help me.
> > 
> > 
> > I'm experiencing the same problem. Could you please let me know how you addressed it? I would really appreciate your help.
> 
> hello, I didn't fix this problem. But I add some code in the source code, to get the result image and save it. It's easy to do it. hope this could help u.



Thank you very much for your helpful advice. I really appreciate it!
