### ISSUE TITLE
模型无法从huggingface下载，

### ISSUE THREAD

**Issue by xiaomiyan160** [zhuang2002/PowerPaint#74]
raise Exception(f'无法从 {url} 下载，错误信息：{str(err.args[0])}')
IndexError: tuple index out of range

  raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

Prompt executed in 1.26 seconds
got prompt
WARNING: '130'
downloading https://hf-mirror.com/runwayml/stable-diffusion-v1-5/resolve/main/text_encoder/model.fp16.safetensors to D:\SD  cola\~ComfyUI-aki(3.14) xingshuai\ComfyUI-aki(3.14)\models\clip\model.fp16.safetensors
无法从huggingface下载，正在尝试从 https://hf-mirror.com/runwayml/stable-diffusion-v1-5/resolve/main/text_encoder/model.fp16.safetensors 下载...
!!! Exception during processing !!! tuple index out of range

**Comment by Chinafsh** [comment]
> raise Exception(f'无法从 {url} 下载，错误信息：{str(err.args[0])}') IndexError: tuple index out of range
> 
> raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 401: Unauthorized
> 
> Prompt executed in 1.26 seconds got prompt WARNING: '130' downloading https://hf-mirror.com/runwayml/stable-diffusion-v1-5/resolve/main/text_encoder/model.fp16.safetensors to D:\SD cola~ComfyUI-aki(3.14) xingshuai\ComfyUI-aki(3.14)\models\clip\model.fp16.safetensors 无法从huggingface下载，正在尝试从 https://hf-mirror.com/runwayml/stable-diffusion-v1-5/resolve/main/text_encoder/model.fp16.safetensors 下载... !!! Exception during processing !!! tuple index out of range

你好，兄弟，提供库的人已经从huggingface上闪库跑路了...

**Comment by minushuang** [comment]
蹲

**Comment by Chinafsh** [comment]
> 蹲

提供一个建议，你可以去宝宝脸上找一个相同版本号的diffusion-model。

**Comment by zengyh1900** [comment]
> > 蹲
> 
> 提供一个建议，你可以去宝宝脸上找一个相同版本号的diffusion-model。

Good suggestion :)
