### ISSUE TITLE
inference code for dev branch

### ISSUE THREAD

**Issue by lucDoom** [zhuang2002/PowerPaint#78]
sorry for creating an issuse again, bcz the last one closed...
I train my own data with dev brach for image outpainting task,  and I write my own inference code from app.py for image outpaiting locally from main brach. But it seems that it does not work on dev brach.
I found that in dev brach there are some changes, eg. there is no more powerpaint.utils.utils.TokenizerWrapper
So can you share new inference code for the dev branch? thanks a lot!

**Comment by zengyh1900** [comment]
Hi @lucDoom 

Sorry for closing your issue! Please feel free to reopen the old issue :)
Regarding your question, I think we have already provided a new [`app.py`](https://github.com/open-mmlab/PowerPaint/blob/dev/app.py) in the `dev branch`.

**Comment by lucDoom** [comment]
@zengyh1900  
oh sry I missed it. I will check this new app.py.Thank you!
