### ISSUE TITLE
hello, can you share the ak:sk of the two data and your annotation files. 

### ISSUE THREAD

**Issue by luotianhang** [zhuang2002/PowerPaint#86]

**Comment by zengyh1900** [comment]
Hi @luotianhang 
Thank you for your interest. I am not the owner of the dataset. You can inquire with people at OpenDataLab and apply for access.

**Comment by zhLawliet** [comment]
@zengyh1900  你好
我下载的laion数据集，每一张图会对应一个json
![image](https://github.com/user-attachments/assets/11f80e98-f61b-4990-a6b6-dcf3bdf53ca7)
问题1：你的laion数据集的提示词是上面json里面的caption吗？
问题2：如果是，我理解anno_info["remark"]是对应上面json，为什么prompt来自anno_info["content"]，而不是来自remark
问题3：如果不是，anno_info["content"]是怎么来的。
问题4：可以提供几个样本和对应的annotation文件吗或者有一个文档能解释一下每一个文件的意义和构建来源，以及每一个字段的意义？方便我们清晰地知道你的数据结构是什么样的。
![image](https://github.com/user-attachments/assets/33f9a160-925b-4dd4-8cfa-cc7af0d3dc9e)

**Comment by zhLawliet** [comment]
@zengyh1900 这个地方的代码好像有点问题，iter(self.dataset_list[idx]) 会报错，因为self.dataset_list里面的是迭代器
PowerPaint/powerpaint/datasets/__init__.py
修改后的代码：
![image](https://github.com/user-attachments/assets/5a2d109f-dc7a-4fd6-bd9f-b7f57928ba49)
