### ISSUE TITLE
 请问，哪里可以拿到LAION Aesthetics v2 5+ 数据集？

### ISSUE THREAD

**Issue by zhLawliet** [zhuang2002/PowerPaint#87]
https://opendatalab.com/OpenDataLab/LAION-5B
https://huggingface.co/laion
在上面的网站上，没有找到评分大于5的LAION Aesthetics v2子集合。

**Comment by zengyh1900** [comment]
hi @zhLawliet 
每个样本有 aesthetics score 可以来筛选

**Comment by zhLawliet** [comment]
@zengyh1900 
1 请问下。能够提供少量的样本实例吗？让我们能先跑起来。如果构建data_info的前处理代码能够提供吗？
2 openimage V6中的prompt是你自己用BLIP跑的吗？有没有已经跑好的对应richer and longer captions？
3 我这边使用img2dataset 工具去下载laion2B-en-aesthetic，发现失败率好高，正常吗？最终你这边使用的有效样本数是多少？
![image](https://github.com/user-attachments/assets/d97e215e-4bd9-4bc4-9f56-782b26adfad8)

**Comment by zengyh1900** [comment]
hi @zhLawliet 
1. 我们也是data team 构建的，我们也没有；其实构建 data_info 的代码怎样都可以的，可以参考 laion 的代码，就是ldm里的；
2. 是的，自己跑的；我这两天看下，可以上传
3. 失败率可能随着时间变化越来越高，本质上是很多url逐渐失效了，不过整体量比较大的花问题应该不大。你也可以找找看是否有合适的镜像

**Comment by zhLawliet** [comment]
好的，非常感谢
@zengyh1900  “可以参考 laion 的代码，就是ldm里的”，这个有具体的链接吗？没有找到处理laion 的代码
https://github.com/CompVis/latent-diffusion
https://github.com/LAION-AI/ldm-finetune

**Comment by zengyh1900** [comment]
hi @zhLawliet 
sorry 应该参考这里：https://github.com/webdataset/webdataset/blob/main/webdataset/compat.py#L332
