### ISSUE TITLE
petrel_client 无法安装

### ISSUE THREAD

**Issue by zhLawliet** [zhuang2002/PowerPaint#88]
pip install petrel_client
这个包好像没法安装？
try:
    from petrel_client.client import Client
except ImportError:
    logger.info("Failed to import petrel_client. Please install it if you are using petrel-oss.")

**Comment by zengyh1900** [comment]
hi @zhLawliet 
如果你不是使用 pertreloss 的，你可以不安装的

**Comment by zhLawliet** [comment]
@zengyh1900 嗯如果要使用，怎么安装呢？ 如果不使用pertreloss 就不进行petrel_client安装，是不是还得修改代码？
![image](https://github.com/user-attachments/assets/a55dded5-6549-4d78-abda-f26ea4ba54cd)

**Comment by zengyh1900** [comment]
@zhLawliet 你们实验室环境是用 pertrloss 吗，如果不是你装了也没用。
基本上这个类你可能还是得根据你的实验环境重写的，基本也就是改个文件读取的逻辑

**Comment by zhLawliet** [comment]
好的，谢谢
