### ISSUE TITLE
Error in Gradio App

### ISSUE THREAD

**Issue by kevnantony** [zhuang2002/PowerPaint#93]
Hi Team, 

When I am trying to use Text Guided Object Inpainting, I am getting the following error on my Gradio app. This is often before the loading bar hits 100% in my terminal. I can't find the error on my terminal either. 

![{8F8876D3-4F14-40D1-B7CF-CEB43A4E5514}](https://github.com/user-attachments/assets/15d6a066-922d-4b23-bad8-12700836f1c8)

![{735D2D53-08C6-499E-A7BC-FC7263F4CE28}](https://github.com/user-attachments/assets/3daaadce-62c6-49af-833b-5c57a09f695e)

**Comment by zengyh1900** [comment]
hi @kevnantony please make sure there is no internet error. Is it normal to run other gradio apps? Or you can save the results locally to check the results.

**Comment by gozeon** [comment]
see https://github.com/open-mmlab/PowerPaint/issues/90

**Comment by kevnantony** [comment]
Worked! Thank you @gozeon @zengyh1900.
