### ISSUE TITLE
模型训练的时候为什么不是realisticVisionV60B1_v51VAE

### ISSUE THREAD

**Issue by zhLawliet** [zhuang2002/PowerPaint#94]
@zengyh1900 你好，我看推理的时候，在初始化StableDiffusionPowerPaintBrushNetPipeline的时候，加载的模型是realisticVisionV60B1_v51VAE，但是训练的时候使用的是runwayml/stable-diffusion-v1-5，为什么训练的时候不直接使用realisticVisionV60B1_v51VAE？
训练的代码：
![image](https://github.com/user-attachments/assets/77a1b14d-d9bd-415b-b780-a472053db7b2)
![image](https://github.com/user-attachments/assets/6bd88cf5-9a29-4326-9edd-0a7edb71360f)
推理的时候：
![image](https://github.com/user-attachments/assets/ce97040a-0837-4ebb-ad86-e2e348b7f60b)

**Comment by zengyh1900** [comment]
@zhLawliet 这是基于 stable-diffusion 的模型特性，只要基于 stable-diffusion 训练的模块，可以通用于任何基于 stable-diffusion finetune 的 base model。你也可以不用 realisticvision 推理，用任何 civitAI 上的其他基于 sd15 训练的模型也可以

**Comment by dongdk** [comment]
想问下，realisticVisionV60B1_v51VAE，用的是哪个链接的？
