### ISSUE TITLE
训练数据集构建问题

### ISSUE THREAD

**Issue by zhLawliet** [zhuang2002/PowerPaint#96]
@zengyh1900 
我下载的laion数据集，每一张图会对应一个json
![image](https://github.com/user-attachments/assets/11f80e98-f61b-4990-a6b6-dcf3bdf53ca7)
问题1：你的laion数据集中，随机mask对应的提示词是上面json里面的caption吗？
问题2：如果是，我理解anno_info["remark"]是对应上面json，为什么prompt来自anno_info["content"]，而不是来自remark
问题3：如果不是，anno_info["content"]是怎么来的，我理解随机mask对应的提示词是不是也得通过blip来获取？
问题4：可以提供几个样本和对应的annotation文件吗或者有一个文档能解释一下每一个文件的意义和构建来源，以及每一个字段的意义？方便我们清晰地知道你的数据结构是什么样的。
![image](https://github.com/user-attachments/assets/33f9a160-925b-4dd4-8cfa-cc7af0d3dc9e)

**Comment by zhLawliet** [comment]
@zengyh1900 
我下载的laion数据集，每一张图会对应一个json
![image](https://github.com/user-attachments/assets/11f80e98-f61b-4990-a6b6-dcf3bdf53ca7)
问题1：你的laion数据集中，随机mask对应的提示词是上面json里面的caption吗？
问题2：如果是，我理解anno_info["remark"]是对应上面json，为什么prompt来自anno_info["content"]，而不是来自remark
问题3：如果不是，anno_info["content"]是怎么来的，我理解随机mask对应的提示词是不是也得通过blip来获取？
问题4：可以提供几个样本和对应的annotation文件吗或者有一个文档能解释一下每一个文件的意义和构建来源，以及每一个字段的意义？方便我们清晰地知道你的数据结构是什么样的。
![image](https://github.com/user-attachments/assets/33f9a160-925b-4dd4-8cfa-cc7af0d3dc9e)

**Comment by zhLawliet** [comment]
@zengyh1900 这个地方的代码好像有点问题，iter(self.dataset_list[idx]) 会报错，因为self.dataset_list里面的是迭代器
PowerPaint/powerpaint/datasets/__init__.py
修改后的代码：
![image](https://github.com/user-attachments/assets/5a2d109f-dc7a-4fd6-bd9f-b7f57928ba49)

**Comment by zhLawliet** [comment]
@zengyh1900 
![image](https://github.com/user-attachments/assets/a1792ced-5423-4691-ba1e-cc2b1693b55d)
请问下，在构建P_obj相关标签的时候，openimage的segmentation mask只是用来获取外接bbox吗？

这里是我制作标签的的一个流程，不知道对不对？
1 第一步根据segmentation mask获取对应的bbox
![image](https://github.com/user-attachments/assets/5d3ff64a-bcd0-4a0f-90cf-4935bf072f2d)
2 第二步根据bbox获取局部区域，并用blip对局部区域进行推理获得描述词caption: a glass of beer
![image](https://github.com/user-attachments/assets/57aa2069-1db9-439f-85cd-16d2054a0152)
3  根据bbox构建模型输入，bbox区域置黑
![image](https://github.com/user-attachments/assets/b97adbc7-fadd-4fa7-ae95-47aedd3bbca4)

**Comment by yeluoo** [comment]
> @zengyh1900 我下载的laion数据集，每一张图会对应一个json ![image](https://private-user-images.githubusercontent.com/17424385/370217425-11f80e98-f61b-4990-a6b6-dcf3bdf53ca7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTU4NDcsIm5iZiI6MTczMTkxNTU0NywicGF0aCI6Ii8xNzQyNDM4NS8zNzAyMTc0MjUtMTFmODBlOTgtZjYxYi00OTkwLWE2YjYtZGNmM2JkZjUzY2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA3MzkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNDk1YTU2NTkxMjAwNjlkMGE4M2FhMzg0ODg0MmQ3MmU4YWI2MmQ4MmZjNjRmYzQxYzJkM2IwMTliMmYxNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yA89jr-JHi3pA4dkkJUken9JddJn0y74582gBoaJmF4) 问题1：你的laion数据集中，随机mask对应的提示词是上面json里面的caption吗？ 问题2：如果是，我理解anno_info["remark"]是对应上面json，为什么prompt来自anno_info["content"]，而不是来自remark 问题3：如果不是，anno_info["content"]是怎么来的，我理解随机mask对应的提示词是不是也得通过blip来获取？ 问题4：可以提供几个样本和对应的annotation文件吗或者有一个文档能解释一下每一个文件的意义和构建来源，以及每一个字段的意义？方便我们清晰地知道你的数据结构是什么样的。 ![image](https://private-user-images.githubusercontent.com/17424385/370219524-33f9a160-925b-4dd4-8cfa-cc7af0d3dc9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTU4NDcsIm5iZiI6MTczMTkxNTU0NywicGF0aCI6Ii8xNzQyNDM4NS8zNzAyMTk1MjQtMzNmOWExNjAtOTI1Yi00ZGQ0LThjZmEtY2M3YWYwZDNkYzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA3MzkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNjk1OTdjNzA2N2M1NTBhMGI1YzIxOWY0NDAyODRiOTIwNjk5NDRiY2ZjNTYyNWM4YjQzZjE3ZjBlOGMwNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dESerFXCN9jR_D_-Tkc1PGGnwcZx7w5EbPg7luXLhS4)

哈喽，你问题解决了吗，能分享一下你的数据集吗，我也遇到相同的问题
